package com.mazadhub.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.math.BigDecimal;
import java.time.Instant;

// A single bid placed on an item
@Entity
@Table(name="bids", indexes={
        @Index(name="idx_bids_item", columnList="item_id"),
        @Index(name="idx_bids_bidder", columnList="bidder_id")
})
public class Bid implements Identifiable
{
    // primary key, generated by the database
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="bid_id")
    private Long id;

    // the auction this bid belongs to
    @ManyToOne(fetch=FetchType.LAZY, optional=false)
    @JoinColumn(name="item_id", nullable=false)
    private Item item;

    // who is behind the bid; hidden from other users
    @ManyToOne(fetch=FetchType.LAZY, optional=false)
    @JoinColumn(name="bidder_id", nullable=false)
    private User bidder;

    // the visible amount of this bid
    @Column(name="amount", nullable=false, precision=12, scale=2)
    private BigDecimal amount;

    @Column(name="bid_time", nullable=false)
    private Instant bidTime=Instant.now();

    // true when the proxy engine placed it, not the user
    @Column(name="is_auto", nullable=false)
    private boolean auto;

    // JPA needs a no-argument constructor
    protected Bid()
    {
        // required by JPA
    }

    // Records one bid on an item
    public Bid(Item item, User bidder, BigDecimal amount, boolean auto)
    {
        this.item=item;
        this.bidder=bidder;
        this.amount=amount;
        this.auto=auto;
    }

    // getters / setters used by the JSF pages and services
    @Override
    public Long getId()
    {
        return id;
    }

    public Item getItem()
    {
        return item;
    }

    public User getBidder()
    {
        return bidder;
    }

    public BigDecimal getAmount()
    {
        return amount;
    }

    public Instant getBidTime()
    {
        return bidTime;
    }

    public boolean isAuto()
    {
        return auto;
    }

    // Two entities are the same row when they share a database id
    @Override
    public boolean equals(Object o)
    {
        if(this==o) return true;
        if(!(o instanceof Bid other)) return false;
        return id!=null&&id.equals(other.id);
    }

    // Constant per class, so an entity keeps its hash after the id is assigned
    @Override
    public int hashCode()
    {
        return getClass().hashCode();
    }
}
