package com.mazadhub.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

// A pre-defined category under which items are listed
@Entity
@Table(name="categories",
        uniqueConstraints=@UniqueConstraint(name="uk_categories_name", columnNames="name"))
public class Category implements Identifiable
{
    // primary key, generated by the database
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="category_id")
    private Long id;

    // unique category name shown in the catalogue
    @Column(name="name", nullable=false, length=80)
    private String name;

    @Column(name="description", length=255)
    private String description;

    // JPA needs a no-argument constructor
    protected Category()
    {
        // required by JPA
    }

    // Creates a new category
    public Category(String name, String description)
    {
        this.name=name;
        this.description=description;
    }

    // getters / setters used by the JSF pages and services
    @Override
    public Long getId()
    {
        return id;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name=name;
    }

    public String getDescription()
    {
        return description;
    }

    public void setDescription(String description)
    {
        this.description=description;
    }

    // Two entities are the same row when they share a database id
    @Override
    public boolean equals(Object o)
    {
        if(this==o) return true;
        if(!(o instanceof Category other)) return false;
        return id!=null&&id.equals(other.id);
    }

    // Constant per class, so an entity keeps its hash after the id is assigned
    @Override
    public int hashCode()
    {
        return getClass().hashCode();
    }
}
