package com.mazadhub.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Enumerated;
import jakarta.persistence.EnumType;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Version;

import java.math.BigDecimal;
import java.time.Instant;

// An item put up for auction
@Entity
@Table(name="items", indexes={
        @Index(name="idx_items_category", columnList="category_id"),
        @Index(name="idx_items_status_end", columnList="status,end_date")
})
public class Item implements Identifiable
{
    // primary key, generated by the database
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="item_id")
    private Long id;

    // who listed the item; loaded lazily
    @ManyToOne(fetch=FetchType.LAZY, optional=false)
    @JoinColumn(name="seller_id", nullable=false)
    private User seller;

    // the catalogue category the item belongs to
    @ManyToOne(fetch=FetchType.LAZY, optional=false)
    @JoinColumn(name="category_id", nullable=false)
    private Category category;

    // the winning bidder, filled in when the auction closes with a sale
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="winner_id")
    private User winner;

    @Column(name="title", nullable=false, length=150)
    private String title;

    @Column(name="description", length=2000)
    private String description;

    @Column(name="image_url", length=255)
    private String imageUrl;

    // opening price set by the seller
    @Column(name="start_price", nullable=false, precision=12, scale=2)
    private BigDecimal startPrice;

    // price the catalogue shows right now
    @Column(name="current_price", nullable=false, precision=12, scale=2)
    private BigDecimal currentPrice;

    // optional: pay this and the auction closes at once
    @Column(name="buy_now_price", precision=12, scale=2)
    private BigDecimal buyNowPrice;

    @Column(name="start_date", nullable=false)
    private Instant startDate=Instant.now();

    // when the scheduler is allowed to close the auction
    @Column(name="end_date", nullable=false)
    private Instant endDate;

    // ACTIVE / SOLD / CLOSED
    @Enumerated(EnumType.STRING)
    @Column(name="status", nullable=false, length=20)
    private ItemStatus status=ItemStatus.ACTIVE;

    // optimistic-locking counter: two bids racing on this row cannot both win
    @Version
    @Column(name="version", nullable=false)
    private Long version;

    // JPA needs a no-argument constructor
    protected Item()
    {
        // required by JPA
    }

    // Creates a new auction; the current price starts at the start price
    public Item(User seller, Category category, String title,
                BigDecimal startPrice, Instant endDate)
    {
        this.seller=seller;
        this.category=category;
        this.title=title;
        this.startPrice=startPrice;
        this.currentPrice=startPrice;
        this.endDate=endDate;
    }

    // getters / setters used by the JSF pages and services
    @Override
    public Long getId()
    {
        return id;
    }

    public User getSeller()
    {
        return seller;
    }

    public void setSeller(User seller)
    {
        this.seller=seller;
    }

    public Category getCategory()
    {
        return category;
    }

    public void setCategory(Category category)
    {
        this.category=category;
    }

    public User getWinner()
    {
        return winner;
    }

    public void setWinner(User winner)
    {
        this.winner=winner;
    }

    public String getTitle()
    {
        return title;
    }

    public void setTitle(String title)
    {
        this.title=title;
    }

    public String getDescription()
    {
        return description;
    }

    public void setDescription(String description)
    {
        this.description=description;
    }

    public String getImageUrl()
    {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl)
    {
        this.imageUrl=imageUrl;
    }

    public BigDecimal getStartPrice()
    {
        return startPrice;
    }

    public void setStartPrice(BigDecimal startPrice)
    {
        this.startPrice=startPrice;
    }

    public BigDecimal getCurrentPrice()
    {
        return currentPrice;
    }

    public void setCurrentPrice(BigDecimal currentPrice)
    {
        this.currentPrice=currentPrice;
    }

    public BigDecimal getBuyNowPrice()
    {
        return buyNowPrice;
    }

    public void setBuyNowPrice(BigDecimal buyNowPrice)
    {
        this.buyNowPrice=buyNowPrice;
    }

    public Instant getStartDate()
    {
        return startDate;
    }

    public void setStartDate(Instant startDate)
    {
        this.startDate=startDate;
    }

    public Instant getEndDate()
    {
        return endDate;
    }

    public void setEndDate(Instant endDate)
    {
        this.endDate=endDate;
    }

    public ItemStatus getStatus()
    {
        return status;
    }

    public void setStatus(ItemStatus status)
    {
        this.status=status;
    }

    public Long getVersion()
    {
        return version;
    }

    // True when the seller offered a buy-now price
    public boolean hasBuyNow()
    {
        return buyNowPrice!=null;
    }

    // Two entities are the same row when they share a database id
    @Override
    public boolean equals(Object o)
    {
        if(this==o) return true;
        if(!(o instanceof Item other)) return false;
        return id!=null&&id.equals(other.id);
    }

    // Constant per class, so an entity keeps its hash after the id is assigned
    @Override
    public int hashCode()
    {
        return getClass().hashCode();
    }
}
