package com.mazadhub.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Enumerated;
import jakarta.persistence.EnumType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.time.Instant;

// A registered system user
@Entity
@Table(name="users",
        uniqueConstraints=@UniqueConstraint(name="uk_users_username", columnNames="username"))
public class User implements Identifiable
{
    // primary key, generated by the database
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="user_id")
    private Long id;

    @Column(name="username", nullable=false, length=50)
    private String username;

    // PBKDF2 hash, never the plain password
    @Column(name="password_hash", nullable=false, length=100)
    private String passwordHash;

    @Column(name="full_name", length=120)
    private String fullName;

    @Column(name="email", length=120)
    private String email;

    @Column(name="phone", length=30)
    private String phone;

    // stored as text (USER / ADMIN) instead of an ordinal
    @Enumerated(EnumType.STRING)
    @Column(name="role", nullable=false, length=20)
    private UserRole role=UserRole.USER;

    @Column(name="created_at", nullable=false, updatable=false)
    private Instant createdAt=Instant.now();

    // JPA needs a no-argument constructor
    protected User()
    {
        // required by JPA
    }

    // Creates a new registered user
    public User(String username, String passwordHash, UserRole role)
    {
        this.username=username;
        this.passwordHash=passwordHash;
        this.role=role;
    }

    // getters / setters used by the JSF pages and services
    @Override
    public Long getId()
    {
        return id;
    }

    public String getUsername()
    {
        return username;
    }

    public void setUsername(String username)
    {
        this.username=username;
    }

    public String getPasswordHash()
    {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash)
    {
        this.passwordHash=passwordHash;
    }

    public String getFullName()
    {
        return fullName;
    }

    public void setFullName(String fullName)
    {
        this.fullName=fullName;
    }

    public String getEmail()
    {
        return email;
    }

    public void setEmail(String email)
    {
        this.email=email;
    }

    public String getPhone()
    {
        return phone;
    }

    public void setPhone(String phone)
    {
        this.phone=phone;
    }

    public UserRole getRole()
    {
        return role;
    }

    public void setRole(UserRole role)
    {
        this.role=role;
    }

    public Instant getCreatedAt()
    {
        return createdAt;
    }

    // Two entities are the same row when they share a database id
    @Override
    public boolean equals(Object o)
    {
        if(this==o) return true;
        if(!(o instanceof User other)) return false;
        return id!=null&&id.equals(other.id);
    }

    // Constant per class, so an entity keeps its hash after the id is assigned
    @Override
    public int hashCode()
    {
        return getClass().hashCode();
    }
}
